### ISSUE TITLE
Appeals process

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/mvc-tck#19]
The TCK Appeals process doesn't match the language recommended by the Spec. committee. Please consider revising your user guide to match the language under Challenges in the TCK Process Guide, under Challenges:
https://jakarta.ee/committees/specification/tckprocess/

**Comment by erdlet** [comment]
@ivargrimstad what needs to be done here? Just adding the required section about challenges?

**Comment by ivargrimstad** [comment]
Yes, just copy the text from the tckprocess, or simply link to it from the document so we don't duplicate
