### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/mvc-tck#21]
Some implementations scan for packages starting with `jakarta`, causing TCK to fail.
After lengthy discussions in the Jakarta EE Platform Team, it has been decided that `jakarta` can not be used as top level package for TCKs. Which means we must change to something else.

We are free to select whatever we like at this point

**Comment by ivargrimstad** [comment]
Let's wait and see how this discussion plays out in the Spec Committee before we decide on anything...

**Comment by chkal** [comment]
@ivargrimstad Ok, sure. Just let us know as soon as there is a final decision.

**Comment by erdlet** [comment]
Seems there is a recommendation now:

```
TCK tests must not be packaged in the jakarta.* namespace. At the current time TCKs may be packaged in any other namespace, however, the namespace format of ee.jakarta.tck.<spec-name> is recommended.
```

**Comment by erdlet** [comment]
We'll do this for 2.1 now to have it done. The effort is low so we can do it before starting the release review
